version: '3.8'

services:

    portfolio-frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        env_file:
            - frontend/.env
        restart: always
        ports:
            - 3000:3000