version: '3.8'

services:

    portfolio-frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        restart: always
        ports:
            - 3000:3000
        networks:
            - portfolio_default

networks:
    portfolio_default:
        external: true